import Link from 'next/link';
import Image from 'next/image';
import { PageShell } from '@/components/Chrome';
import { Eyebrow, PageHero } from '@/components/PageHero';

export default function AboutPage() {
  return <PageShell>
    <PageHero eyebrow="About Spaceworks" title={<>A design practice built around <span className="gradient-text">responsibility.</span></>} intro="Spaceworks Design & Build is a multidisciplinary practice based in Pune, bringing architecture, interiors, landscape and project management into one connected way of working." variant={3} />
    <section className="section bg-[var(--paper)]"><div className="container grid lg:grid-cols-[.85fr_1.15fr] gap-14"><div><Eyebrow>Our position</Eyebrow><h2 className="section-title">Creative enough to imagine.<br />Practical enough to deliver.</h2></div><div className="body-copy max-w-3xl space-y-6"><p>We want the studio to feel more human than transactional. More deliberate than decorative. More curious than formulaic.</p><p>But a strong point of view is only valuable when it survives budgets, timelines, coordination, detailing and construction.</p></div></div></section>
    <section className="section bg-[var(--stone)]"><div className="container founder-layout"><div className="founder-portrait"><Image src="/sharan-biradar.png" alt="Sharan Biradar, founder of Spaceworks" width={768} height={768} /></div><div className="founder-story"><Eyebrow>Founder</Eyebrow><p className="mt-4 text-sm uppercase tracking-[.12em] text-[var(--muted)]">Sharan Biradar · Founder</p><h2 className="founder-quote mt-8">A practice shaped by care.</h2><p>Sharan Biradar founded Spaceworks around a simple ambition: bring design thinking and the realities of building closer together, so an idea can become a place people live, work and belong in.</p><p>For Spaceworks, every project begins with listening—to the people, the place and the practical brief. From the first spatial decisions to the details on site, the aim is to make the process clearer and the finished place more meaningful.</p></div></div></section>
    <section className="section bg-[var(--stone-2)]"><div className="container"><Eyebrow>How trust is built</Eyebrow><div className="grid md:grid-cols-4 gap-6 mt-8">{['Listening','Documentation','Coordination','Follow-through'].map((x,i)=><div key={x} className="border-t border-[var(--line)] pt-5"><span className="number">0{i+1}</span><h3 className="mt-3 text-xl font-bold">{x}</h3><p className="body-copy text-sm mt-3">A simple promise: do the unglamorous work properly, because that is where confidence is earned.</p></div>)}</div></div></section>
    <section className="section bg-[var(--ink)] text-white"><div className="container grid lg:grid-cols-[1fr_.9fr] gap-14"><div><Eyebrow dark>For clients</Eyebrow><h2 className="section-title">You should know who owns the next decision.</h2></div><div className="text-white/55 leading-8 text-base md:text-lg space-y-6"><p>As the site grows with real projects, the website can show more evidence: team profiles, consultant relationships, project timelines, material studies, site photographs, testimonials and completed work.</p><p>Until then, we should not invent proof. The design itself can still communicate discipline.</p></div></div></section>
    <section className="section bg-[var(--paper)]"><div className="container text-center"><Eyebrow>Next</Eyebrow><h2 className="section-title">See what the process looks like.</h2><Link href="/design" className="editorial-link mt-8">Explore the design method <span>↗</span></Link></div></section>
  </PageShell>;
}
